2024-06-26 02:04:47,378 ERROR: Exception on /index [GET] [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\routes.py", line 39, in index
    return render_template('index.html', title='Home', username=username, role_message=role_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\templates\index.html", line 23, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2024-06-26 02:05:00,086 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 09:40:48,080 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 10:11:15,774 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 10:12:56,875 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 10:13:04,629 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 10:13:18,732 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 10:48:30,818 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 10:51:45,130 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:01:21,294 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:03:41,924 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:14:44,184 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:15:51,500 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:17:32,635 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:19:10,480 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:19:55,923 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:20:38,742 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:23:15,505 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:24:01,776 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:40:12,362 INFO: Microblog startup [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\__init__.py:45]
2024-06-26 11:40:24,031 ERROR: Exception on /job/1 [GET] [in C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\routes.py", line 233, in job_detail
    return render_template('job_detail.html', job=job)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\templates\job_detail.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\templates\base.html", line 111, in top-level template code
    {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\app\templates\job_detail.html", line 19, in block 'content'
    <form method="POST" action="{{ url_for('apply_job', job_id=job.id) }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\flask\app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06atm\OneDrive\Masaüstü\B.P. 4.dönem\OOP II\microblog\venv\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'apply_job' with values ['job_id']. Did you mean 'post_job' instead?
